version: '3.1'
services:
  API:
    image: 'sample-spring-app'
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/pam
      - SPRING_DATASOURCE_USERNAME=pam
      - SPRING_DATASOURCE_PASSWORD=pam
  PostgreSQL:
    image: nlmacamp/postgres-pljava
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Pass2020!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5