<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Personal Asset Manager</title>
</head>
<body>
<div style="margin-top: 10px">Welcome, ${userFullName}!</div>
<div>Click the following link to complete the registration of email ${userEmail} as the logon to Personal Asset Manager (PAM)</div>
<div><a href="${validationLink}">Click to Complete Registraton</a></div>
<br/>
<div> Have a nice day..!</div>
</body>
</html>